# configs/experiment.yaml

# ========================
# Data settings
# ========================
data:
  parquet: /data/scratch/bty414/opentarget_evidences/kg_output/edges/sourceId=chembl.parquet
  cutoff: 2015
  horizon: 5
  cold_start_file: /data/scratch/bty414/opentarget_evidences/cold_start_diseases.csv
  graph_file: /data/scratch/bty414/opentarget_evidences/kg_output/hetero_graph_2010_5.pt
  node_dir: /data/scratch/bty414/opentarget_evidences/kg_output/nodes/
  edge_dir: /data/scratch/bty414/opentarget_evidences/kg_output/edges/
  disease_nodes: /data/scratch/bty414/opentarget_evidences/kg_output/nodes/diseases.parquet   # users
  target_nodes: /data/scratch/bty414/opentarget_evidences/kg_output/nodes/targets.parquet     # items

# ========================
# Model settings
# ========================
model:
  name: ncf        # options: [ncf, graph]
  embed_dim: 64
  loss_type: mse   # [bce, mse]
  supervision_src_type: diseases
  supervision_dst_type: targets
  supervision_relation_type: clinical_trial

# ========================
# Training settings
# ========================
train:
  epochs: 10
  batch_size: 512
  lr: 1e-3
  seed: 42
  num_neg: 1

# ========================
# Evaluation settings
# ========================
eval:
  num_eval_negs: 1000
  topk: [10, 50]
  metrics: ["Recall", "NDCG"]
  valid_metric: NDCG@10
