# TODO: consider resource score or score for downstream process
# are there duplicate evidences where source and target and relation are the same?

# for each edge, we log the properties evidence_id (id), score, literature, publicationYear for temporal tracing back to evidence

sourceId=cancer_biomarkers:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

# chembl_drug_disease.yaml
sourceId=chembl:
  - source: drugId
    target: diseaseId
    relation: datatypeId
    relation_name: clinical_trial
    props: [score, literature, publicationYear, id]

  - source: drugId
    target: targetId
    relation: datatypeId
    relation_name: modulated_by
    props: [score, literature, publicationYear, id]

# provide direct and mechanistic edge for pathway related
sourceId=reactome:
  - source: targetId
    target: diseaseId
    relation: datatypeId
    props: [score, literature, publicationYear, id]
    
  - source: targetId
    target: pathways.id
    relation: datatypeId
    relation_name: involved_in_pathway
    props: [score, literature, publicationYear, id]

  - source: pathways.id
    target: diseaseId
    relation: datatypeId
    relation_name: pathway_associated_with
    props: [score, literature, publicationYear, id]

sourceId=clingen:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

# variant as node?
sourceId=eva:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=gene_burden:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=intogen:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

# provide direct and mechanistic edge for pathway related
sourceId=slapenrich:
  - source: targetId
    target: diseaseId
    relation: datatypeId
    props: [score, literature, publicationYear, id]

  - source: targetId
    target: pathways.id
    relation: datatypeId
    relation_name: involved_in_pathway
    props: [score, literature, publicationYear, id]

  - source: pathways.id
    target: diseaseId
    relation: datatypeId
    relation_name: pathway_associated_with
    props: [score, literature, publicationYear, id]

sourceId=crispr:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=eva_somatic:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=genomics_england:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=orphanet:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=sysbio:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=cancer_gene_census:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=crispr_screen:
  source: targetId
  target: diseaseId
  relation: datatypeId
  prop: [cellType, score, literature, publicationYear, id]

sourceId=expression_atlas:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

# pathways as nodes?
sourceId=progeny:
  - source: targetId
    target: diseaseId
    relation: datatypeId
    props: [score, literature, publicationYear, id]

  - source: targetId
    target: pathways.id
    relation: datatypeId
    relation_name: involved_in_pathway
    props: [score, literature, publicationYear, id]

  - source: pathways.id
    target: diseaseId
    relation: datatypeId
    relation_name: pathway_associated_with
    props: [score, literature, publicationYear, id]

sourceId=uniprot_literature:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=europepmc:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=gene2phenotype:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

# phenotypes as nodes?
sourceId=impc:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]

sourceId=uniprot_variants:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [score, literature, publicationYear, id]
