# TODO: what about edges with no temporal information? e.g. intogen, progeny (supp file temporal trend)

sourceId=cancer_biomarkers:
  name: cancer_biomarker
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=chembl:
  - name: chembl
    sourceId: diseaseId
    targetId: targetId
    relation_name: clinical_trial
    props: [source_type=constant:disease, target_type=constant:target, datasourceId, score, year, id]

  - name: chembl
    sourceId: drugId
    targetId: targetId
    relation_name: modulated_by
    props: [source_type=constant:molecule, target_type=constant:target, datasourceId, score, year, id]

sourceId=reactome:
  - name: reactome
    sourceId: targetId
    targetId: diseaseId
    relation: datatypeId
    props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

  - name: reactome
    sourceId: targetId
    targetId: pathways.id
    relation_name: involved_in
    props: [source_type=constant:target, target_type=constant:reactome, datasourceId, score, year, id]

  - name: reactome
    sourceId: diseaseId
    targetId: pathways.id
    relation: datatypeId
    relation_name: associated_with
    props: [source_type=constant:disease, target_type=constant:reactome, datasourceId, score, year, id]

sourceId=clingen:
  name: clingen
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=eva:
  name: eva
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=gene_burden:
  name: gene_burden
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

# sourceId=intogen:
#   name: intogen
#   sourceId: targetId
#   targetId: diseaseId
#   relation: datatypeId
#   props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=slapenrich:
  
  - sourceId: targetId
    targetId: diseaseId
    relation: datatypeId
    props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

  - sourceId: targetId
    targetId: pathways.id
    relation_name: involved_in
    props: [source_type=constant:target, target_type=constant:reactome, datasourceId, score, year, id]

  - sourceId: diseaseId
    targetId: pathways.id
    relation_name: associated_with
    props: [source_type=constant:disease, target_type=constant:reactome, datasourceId, score, year, id]

sourceId=crispr:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=eva_somatic:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=genomics_england:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=orphanet:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=sysbio:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=cancer_gene_census:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=crispr_screen:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, cellType, datasourceId, score, year, id]

sourceId=expression_atlas:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

# sourceId=progeny:
#   - sourceId: targetId
#     targetId: diseaseId
#     relation: datatypeId
#     props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

#   - sourceId: targetId
#     targetId: pathways.id
#     relation_name: involved_in
#     props: [source_type=constant:target, target_type=constant:reactome, datasourceId, score, year, id]

#   - sourceId: diseaseId
#     targetId: pathways.id
#     relation: datatypeId
#     props: [source_type=constant:disease, target_type=constant:reactome, datasourceId, score, year, id]

sourceId=uniprot_literature:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=europepmc:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=gene2phenotype:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=impc:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]

sourceId=uniprot_variants:
  sourceId: targetId
  targetId: diseaseId
  relation: datatypeId
  props: [source_type=constant:target, target_type=constant:disease, datasourceId, score, year, id]
