targets:
  id: id
  name: approvedSymbol
  props: [biotype, approvedName]

diseases:
  id: id
  name: diseaseFromSource
  props: [description, therapeuticAreas]

molecule:
  id: id
  props: [maximumClinicalTrialPhase]

reactome:
  id: id
  name: label
  props: [ancestors, descendants]

go:
  id: id
  name: name
