# Progression Graph Configuration

time_range:
  first_year: 2000
  last_year: 2025

data_sources:
  gwas_credible_sets:
    datatype: genetic_association
    weight: 1.0
  eva:
    datatype: genetic_association
    weight: 1.0
  gene_burden:
    datatype: genetic_association
    weight: 1.0
  genomics_england:
    datatype: genetic_association
    weight: 1.0
  gene2phenotype:
    datatype: genetic_association
    weight: 1.0
  uniprot_literature:
    datatype: genetic_association
    weight: 1.0
  uniprot_variants:
    datatype: genetic_association
    weight: 1.0
  orphanet:
    datatype: genetic_association
    weight: 1.0
  clingen:
    datatype: genetic_association
    weight: 1.0
  cancer_gene_census:
    datatype: somatic_mutation
    weight: 1.0
  intogen:
    datatype: somatic_mutation
    weight: 1.0
  eva_somatic:
    datatype: somatic_mutation
    weight: 1.0
  cancer_biomarkers:
    datatype: somatic_mutation
    weight: 1.0
  chembl:
    datatype: known_drug
    weight: 1.0
  crispr_screen:
    datatype: affected_pathway
    weight: 1.0
  crispr:
    datatype: affected_pathway
    weight: 1.0
  slapenrich:
    datatype: affected_pathway
    weight: 0.5
  progeny:
    datatype: affected_pathway
    weight: 0.5
  reactome:
    datatype: affected_pathway
    weight: 1.0
  sysbio:
    datatype: affected_pathway
    weight: 0.5
  europepmc:
    datatype: literature
    weight: 0.2
    cutoff: 0.3
  expression_atlas:
    datatype: rna_expression
    weight: 0.2
  impc:
    datatype: animal_model
    weight: 0.2
  gene_ontology:
    datatype: functional_annotation
    weight: 1.0
