diseases:
  input_dir: diseases
  name: disease_disease_ontology_disease
  sourceId: id
  targetId: parents
  relation_name: is_subtype_of
  props: [
    datasourceId=constant:disease_ontology,
    score=constant:1.0,
    source_type=constant:disease,
    target_type=constant:disease
  ]

reactome:
  input_dir: reactome
  name: reactome_reactome_pathway_reactome
  sourceId: id
  targetId: parents
  relation_name: is_subpathway_of
  props: [
    datasourceId=constant:reactome,
    score=constant:1.0,
    source_type=constant:reactome,
    target_type=constant:reactome
  ]